---
ID: "bc6926a0-397c-4f54-88fa-ce2aedbd7888"
Parent: "5bfe0cbe-4bbe-4b34-b17a-50f76002baa9"
Template: "5bfe0cbe-4bbe-4b34-b17a-50f76002baa9"
Path: /sitecore/templates/Feature/Content/Rendering Parameters/Card/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "821fd413-3467-436d-8947-8befec306629"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240128T080936Z
