---
ID: "0b4e0d63-1761-43c8-ab2a-9dec8952755e"
Parent: "a1737eaa-849f-422a-8e10-45c456c7288f"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: /sitecore/content/Hahn Solo/Sitecore Community/Presentation/Partial Designs/Products
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: products
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{EE6629CF-06C9-44A5-A4E7-17EBEC9F75FC}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{15ACAC7C-7CB3-4461-BA82-CAE9F02ACB4F}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="FieldNames&amp;RenderingIdentifier&amp;Styles=%7C%7B1FEDB34F-9F9D-4FBC-8BDC-DC896D541E42%7D&amp;BackgroundImage&amp;CSSStyles&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;DynamicPlaceholderId=1&amp;CacheClearingBehavior=Clear%20on%20publish"
              s:ph="headless-main" />
            <r
              uid="{9C711DE3-C2B9-444E-A38A-E20DC2147D6E}"
              p:after="r[@uid='{15ACAC7C-7CB3-4461-BA82-CAE9F02ACB4F}']"
              s:ds=""
              s:id="{7892ACB1-05DD-4E7D-B57F-725C45D7E993}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3&amp;CacheClearingBehavior=Clear%20on%20publish"
              s:ph="/headless-main/container-1" />
            <r
              uid="{92081210-80A6-4436-8EAB-FF06A5540543}"
              p:after="r[@uid='{9C711DE3-C2B9-444E-A38A-E20DC2147D6E}']"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="FieldNames&amp;RenderingIdentifier&amp;Styles&amp;BackgroundImage&amp;CSSStyles&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;DynamicPlaceholderId=2&amp;CacheClearingBehavior=Clear%20on%20publish"
              s:ph="headless-main" />
            <r
              uid="{048EE63D-3570-48EA-B2C4-98B434FD819B}"
              p:after="*[1=2]"
              s:ds="local:/Data/Breadcrumb 1"
              s:id="{CDB1CD0C-F93A-4383-BC66-54BCCCD03033}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240117T144221Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Christian Hahn
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Christian Hahn
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "120e536e-cb2f-46be-91a8-222fb8213058"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Christian Hahn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240807T135936Z
