---
ID: "4ae077a3-97e2-47cd-9c98-2dec2c293da6"
Parent: "5b4409fa-6183-4d5d-9e3c-d4d58eeee540"
Template: "5b4409fa-6183-4d5d-9e3c-d4d58eeee540"
Path: /sitecore/templates/Feature/Content/Folders/Card Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {91DA1426-2BF0-4A5D-BC84-24B3B449EA6D}
    {5B4409FA-6183-4D5D-9E3C-D4D58EEEE540}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b39cf00c-acbf-4aed-a260-50aeac287abb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240128T080938Z
