---
ID: "8b2c2c54-a2fc-4284-882d-cf49592c8e73"
Parent: "4719b9a1-47e7-4f01-a92c-017a3dc4cb80"
Template: "4719b9a1-47e7-4f01-a92c-017a3dc4cb80"
Path: /sitecore/templates/Feature/Products/Datasources/_product/__Standard Values
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221226T150436Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "790f0098-ab15-47e1-b989-8e82b10ec2e4"
      Hint: ProductImageAspectRatio
      Value: 1.333
    - ID: "857fde69-864e-4c83-b802-9dbef010cc2c"
      Hint: ProductId
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2c699ee1-57ce-4a15-b1cf-0a90345ca684"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230904T130808Z
