---
ID: "1b6bc7d0-6a9e-4ad7-b00b-9b2fa24386fb"
Parent: "009b22c0-468e-46a8-90cc-1059b29c822b"
Template: "bed31d6f-d968-45a9-b54e-12d7f977d861"
Path: /sitecore/system/Settings/Feature/Products/Products Site Setup
SharedFields:
- ID: "40deee2f-7595-40bd-b2c9-51f9e2346100"
  Hint: Dependencies
  Value: "{C4D79D81-83E9-4506-AE8C-F7145C75762F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221226T142214Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a77c940c-35ec-41cc-991a-449d69547d0a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "c202067e-7fab-4606-afb4-e76df2185ddc"
      Hint: Name
      Value: Products
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230313T091643Z
