---
ID: "490ade65-0b2f-4c35-8e38-4cd3f2ba338c"
Parent: "6f2f67e0-99bd-403e-90bf-cf83499d016a"
Template: "6f2f67e0-99bd-403e-90bf-cf83499d016a"
Path: /sitecore/templates/Foundation/AI/Datasources/AI Action/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231012T170714Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "76e19d64-0c86-4f2c-bb2c-66e21fc39c1c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tzoxyd3zg1
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231012T170714Z
