---
ID: "df3c5bcb-8e22-42d9-9dc6-f6cf62ac9dad"
Parent: "d1303f02-8832-4eab-b0e9-89b78d3a672d"
Template: "473d4a8a-5fbf-461c-a52c-e01316da7e1d"
Path: "/sitecore/content/Hahn Solo/The-Magic-of-AI/Settings/Products"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240202T114751Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Christian Hahn
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Christian Hahn
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "54246be5-2239-4f20-b398-d71a0d965287"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Christian Hahn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240202T114751Z
