---
ID: "9b3b0bf6-04cb-42d0-8f5d-d15321212135"
Parent: "4c1b1dcd-08cc-4d1f-82c3-72fda2d538f9"
Template: "4c1b1dcd-08cc-4d1f-82c3-72fda2d538f9"
Path: /sitecore/templates/Feature/Authentication/Folders/Global Roles Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{291B6C5A-FB76-452F-88FF-4CEE544458DE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20221231T111629Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "96f781cb-9f9f-463f-a8b8-61680e0e607a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Christian Hahn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240617T122839Z
