---
ID: "b96d69db-9230-429a-93be-6c2c24481b22"
Parent: "5427316e-bd00-4d27-88ac-232b363cebe2"
Template: "267d9ac7-5d85-4e9d-af89-99ab296cc218"
Path: "/sitecore/content/Hahn Solo/The-Magic-of-AI/Dictionary/Products"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230731T075723Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcfb0684-884f-4976-a801-8fa64a5ba5e7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Christian Hahn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240202T114756Z
