---
ID: "0e1ec811-7056-4f81-8287-893b907d3718"
Parent: "dc42cb2e-13da-4289-b825-1c18362eeae6"
Template: "dc42cb2e-13da-4289-b825-1c18362eeae6"
Path: /sitecore/templates/Feature/Seo/Datasources/_openGraph/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230604T171310Z
    - ID: "505bce75-e9b7-493a-9c01-4d3d85982d3c"
      Hint: OgTitlte
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d72787e0-bffc-4f0e-ba07-73f98809563d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\christian.hahn@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230604T171314Z
